export const partyColours = {
    "Aam Aadmi Party": "#0072b0",
    "All India Anna Dravida Munnetra Kazhagam": "#009546",
    "All India Majlis-E-Ittehadul Muslimeen": "#0c6b4b",
    "All India Trinamool Congress": "#20c646",
    "All India United Democratic Front": "#348017",
    "All Jharkhand Students Union": "#6827b5",
    "Apna Dal (Soneylal)": "#27176d",
    "Bahujan Samaj Party": "#22409a",
    "Bharatiya Janta Party": "#ff9933",
    "Biju Janata Dal": "#70a548",
    "Communist Party Of India": "#cb0922",
    "Communist Party Of India (Marxist)": "#cc0d0d",
    "Dravida Munetra Kazhagam": "#ff0d0d",
    Independent: "black",
    "Indian National Congress": "#19aaed",
    "Indian Union Muslim League": "#006600",
    "Jammu & Kashmir National Conference": "#fe0000",
    "Janata Dal (Secular)": "#02865a",
    "Janata Dal (United)": "#003366",
    "Jharkhand Mukti Morcha": "#337316",
    "Kerala Congress(M)": "#f48385",
    "Lok Jan Shakti Party": "#5b006a",
    "Mizo National Front": "#2e5694",
    "Naga Peoples Front": "#1717cc",
    "National People's Party": "#ffca61",
    "Nationalist Congress Party": "#00b2b2",
    "Nationalist Democratic Progressive Party": "#ed1b24",
    "Rashtriya Loktantrik Party": "#ffd42a",
    "Revolutionary Socialist Party": "#d84c4c",
    "Samajwadi Party": "#ff2222",
    "Shiromani Akali Dal": "#0f204a",
    "Shiv Sena": "#f37020",
    "Sikkim Krantikari Morcha": "#ed1e26",
    "Telangana Rashtra Samithi": "#f84996",
    "Telugu Desam": "#ffed00",
    "Viduthalai Chiruthaigal Katchi": "#0000ff",
    "Yuvajana Sramika Rythu Congress Party": "#1569c7",
};

// window.partyColours = partyColours;